# Generated by Django 5.0.6 on 2024-06-30 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='images',
            new_name='image',
        ),
    ]
