# Generated by Django 5.0.6 on 2024-06-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_rename_images_bid_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
