# Generated by Django 5.0.6 on 2024-06-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_bid_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_auction',
            name='Description',
            field=models.CharField(default='default', max_length=9999999),
        ),
        migrations.AddField(
            model_name='list_auction',
            name='Image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='list_auction',
            name='Starting_bid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='list_auction',
            name='Title',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='list_auction',
            name='Username',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AddField(
            model_name='list_auction',
            name='username_watch',
            field=models.CharField(default='default_username', max_length=100),
        ),
    ]
