# Generated by Django 5.0.6 on 2024-07-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_list_auction_description_list_auction_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='UID',
            field=models.TextField(default='DE000'),
        ),
        migrations.AddField(
            model_name='list_auction',
            name='UID',
            field=models.TextField(default='DE000'),
        ),
    ]
