# Generated by Django 5.0.6 on 2024-07-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid_uid_list_auction_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_auction',
            name='Image',
            field=models.ImageField(null=True, upload_to='images_watchlist/'),
        ),
    ]
