# Generated by Django 5.0.6 on 2024-07-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_list_auction_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='bid_tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UID', models.TextField(default='DE000')),
                ('allBids', models.IntegerField(default=0)),
            ],
        ),
    ]
