# Generated by Django 5.0.6 on 2024-07-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid_tracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid_tracker',
            old_name='allBids',
            new_name='Bid_amount',
        ),
        migrations.AddField(
            model_name='bid_tracker',
            name='bidder',
            field=models.TextField(default='dummy', max_length=100),
        ),
    ]
