# Generated by Django 5.0.6 on 2024-07-03 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_bid_contact_id_bid_number_of_buyers_before_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='description',
            new_name='short_description',
        ),
    ]
