# Generated by Django 5.0.6 on 2024-07-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_bid_contact_id_bid_number_of_buyers_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid_comments',
            name='username',
            field=models.TextField(default='Nothing'),
        ),
    ]
