# Generated by Django 5.0.6 on 2024-07-03 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_rename_uid_bid_tracker_unique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid_comments',
            old_name='UID',
            new_name='Unique',
        ),
        migrations.RenameField(
            model_name='bid_tracker',
            old_name='Unique',
            new_name='UID',
        ),
    ]
