# Generated by Django 5.0.6 on 2024-07-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_rename_uid_bid_comments_unique_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid_comments',
            old_name='Unique',
            new_name='UID',
        ),
    ]
